package com.kite.di.processor.codegen

import com.kite.di.processor.model.ViewModelModel
import com.kite.di.processor.model.ViewModelParam
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.LambdaTypeName
import com.squareup.kotlinpoet.MemberName
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy

/**
 * Emits the per-ViewModel call-site adapters:
 *
 * ```kotlin
 * private val counter by counterViewModel()               // in an Activity or Fragment
 * private val checkout by checkoutViewModel(orderId)      // runtime args are parameters
 * ```
 *
 * The androidx ViewModelStore retains the instance; the generated lambda builds it
 * once — graph dependencies resolved against the caller's scope, `SavedStateHandle`
 * from CreationExtras, runtime arguments captured from the call.
 */
object AdapterGenerator {

    private val COMPONENT_ACTIVITY = ClassName("androidx.activity", "ComponentActivity")
    private val FRAGMENT = ClassName("androidx.fragment.app", "Fragment")
    private val LAZY = ClassName("kotlin", "Lazy")
    private val LAZY_OF = MemberName("kotlin", "lazy")
    private val LAZY_MODE = ClassName("kotlin", "LazyThreadSafetyMode")
    private val RESOLVE_VIEW_MODEL = MemberName("com.kite.di.runtime.android", "resolveViewModel")
    private val CREATE_SAVED_STATE = MemberName("androidx.lifecycle", "createSavedStateHandle")
    private val COMPOSABLE = ClassName("androidx.compose.runtime", "Composable")
    private val INJECTED_VIEW_MODEL = MemberName("com.kite.di.compose", "injectedViewModel")

    fun adapterFile(vm: ViewModelModel, compose: Boolean = false): FileSpec {
        val fileName = vm.targetType.simpleNames.joinToString("_") + "_Adapters"
        val file = FileSpec.builder(vm.targetType.packageName, fileName)
            .addFileComment("Generated by the Kite processor from %L — do not edit.", vm.targetType.displayName)
            .addFunction(adapterFun(vm, COMPONENT_ACTIVITY))
            .addFunction(adapterFun(vm, FRAGMENT))
        if (compose) file.addFunction(composeAdapterFun(vm))
        return file.build()
    }

    /**
     * The Compose adapter — emitted only when the module has Compose enabled:
     *
     * ```kotlin
     * val counter = rememberCounterViewModel()      // in any @Composable
     * ```
     *
     * The nearest LocalViewModelStoreOwner (NavBackStackEntry, Fragment, Activity)
     * retains the instance; graph dependencies resolve against the host Activity's scope.
     */
    private fun composeAdapterFun(vm: ViewModelModel): FunSpec {
        val vmType = ClassName(vm.targetType.packageName, vm.targetType.simpleNames)
        val name = "remember" + vm.targetType.simpleNames.joinToString("")
        val fn = FunSpec.builder(name)
            .addAnnotation(COMPOSABLE)
            .returns(vmType)
        for (param in vm.params.filterIsInstance<ViewModelParam.Runtime>()) {
            fn.addParameter(param.name, param.type.className())
        }
        fn.addCode(
            CodeBlock.builder()
                .add("return %M(%T::class.java) { resolver, scope, extras ->\n", INJECTED_VIEW_MODEL, vmType)
                .indent()
                .add("%T(\n", vmType)
                .indent()
                .add(construction(vm))
                .unindent()
                .add(")\n")
                .unindent()
                .add("}\n")
                .build()
        )
        return fn.build()
    }

    private fun adapterFun(vm: ViewModelModel, receiver: ClassName): FunSpec {
        val vmType = ClassName(vm.targetType.packageName, vm.targetType.simpleNames)
        val fn = FunSpec.builder(vm.adapterName)
            .receiver(receiver)
            .returns(LAZY.parameterizedBy(vmType))
        for (param in vm.params.filterIsInstance<ViewModelParam.Runtime>()) {
            fn.addParameter(param.name, param.type.className())
        }

        fn.addCode(
            CodeBlock.builder()
                .add("return %M(%T.NONE) {\n", LAZY_OF, LAZY_MODE)
                .indent()
                .add("%M(this, this, %T::class.java) { resolver, scope, extras ->\n", RESOLVE_VIEW_MODEL, vmType)
                .indent()
                .add("%T(\n", vmType)
                .indent()
                .add(construction(vm))
                .unindent()
                .add(")\n")
                .unindent()
                .add("}\n")
                .unindent()
                .add("}\n")
                .build()
        )
        return fn.build()
    }

    /** The constructor call shared by all adapter shapes — one line per parameter, in order. */
    private fun construction(vm: ViewModelModel): CodeBlock {
        val construction = CodeBlock.builder()
        for (param in vm.params) {
            when (param) {
                is ViewModelParam.Injected ->
                    construction.add("%L = %L,\n", param.name, FactoryGenerator.resolveExpression(param.dependency))
                is ViewModelParam.Runtime ->
                    construction.add("%L = %L,\n", param.name, param.name)
                is ViewModelParam.SavedState ->
                    construction.add("%L = extras.%M(),\n", param.name, CREATE_SAVED_STATE)
            }
        }
        return construction.build()
    }
}
