package com.kite.di.processor.codegen

import com.kite.di.graph.DeferredKind
import com.kite.di.graph.Key
import com.kite.di.processor.model.BindingDeclKind
import com.kite.di.processor.model.BindingModel
import com.kite.di.processor.model.DependencyModel
import com.kite.di.processor.model.MemberInjectModel
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.MAP
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.SET
import com.squareup.kotlinpoet.STRING
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec

/**
 * Emits one reflection-free `<Type>_Factory` per binding and one
 * `<Type>_MemberInjector` per @Inject-field target, in the target's own package
 * (so `internal` classes stay accessible).
 */
object FactoryGenerator {

    fun factoryFile(binding: BindingModel, availableKeys: Set<Key>): FileSpec {
        val producedType = binding.keyType.className()
        val create = FunSpec.builder("create")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("resolver", RuntimeNames.RESOLVER)
            .addParameter("scope", RuntimeNames.SCOPE_NODE)
            .returns(producedType)

        val args = CodeBlock.builder()
        val included = binding.dependencies.filter { !it.optional || it.key in availableKeys }
        for (dep in included) {
            // Named arguments so optional params with missing bindings can be omitted.
            args.add("%L = %L,\n", dep.paramName, resolveExpression(dep))
        }

        val callArgs = CodeBlock.builder().add("(\n").indent().add(args.build()).unindent().add(")")
        val body = when (binding.declKind) {
            BindingDeclKind.INJECTABLE ->
                CodeBlock.builder().add("return %T", binding.targetType.className()).add(callArgs.build()).build()
            BindingDeclKind.PROVIDES -> {
                val receiver = if (binding.moduleIsObject) {
                    CodeBlock.of("%T", binding.targetType.className())
                } else {
                    CodeBlock.of("module")
                }
                CodeBlock.builder().add("return %L.%L", receiver, binding.providesFunction).add(callArgs.build()).build()
            }
        }
        create.addCode(body)

        val type = TypeSpec.classBuilder(binding.factoryName)
            .addKdoc("Generated by the Kite processor from %L — do not edit.", binding.declaration)
            .addSuperinterface(RuntimeNames.FACTORY.parameterizedBy(producedType))
            .addFunction(create.build())
        if (binding.declKind == BindingDeclKind.PROVIDES && !binding.moduleIsObject) {
            type.addProperty(
                PropertySpec.builder("module", binding.targetType.className(), KModifier.PRIVATE)
                    .initializer("%T()", binding.targetType.className())
                    .build()
            )
        }
        return FileSpec.builder(binding.factoryPackage, binding.factoryName)
            .addType(type.build())
            .build()
    }

    fun memberInjectorFile(model: MemberInjectModel): FileSpec {
        val target = model.targetType.className()
        val inject = FunSpec.builder("inject")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("target", target)
            .addParameter("resolver", RuntimeNames.RESOLVER)
            .addParameter("scope", RuntimeNames.SCOPE_NODE)
        for (field in model.fields) {
            inject.addCode(
                "target.%L = %L\n",
                field.fieldName,
                resolveExpression(
                    keyLiteral(field.type.className(), field.key.qualifier),
                    field.type.className(),
                    field.deferred,
                ),
            )
        }
        val type = TypeSpec.classBuilder(model.injectorName)
            .addKdoc("Generated by the Kite processor — do not edit.")
            .addSuperinterface(RuntimeNames.MEMBER_INJECTOR.parameterizedBy(target))
            .addFunction(inject.build())
        return FileSpec.builder(model.targetType.packageName, model.injectorName)
            .addType(type.build())
            .build()
    }

    private fun resolveExpression(dep: DependencyModel): CodeBlock {
        val type: TypeName = dep.setElement?.let { SET.parameterizedBy(it.className()) }
            ?: dep.mapValue?.let { MAP.parameterizedBy(STRING, it.className()) }
            ?: dep.type.className()
        val key = dep.setElement?.let { keyLiteral(SET, dep.key.qualifier, element = it.className()) }
            ?: dep.mapValue?.let { keyLiteral(MAP, dep.key.qualifier, mapValue = it.className()) }
            ?: keyLiteral(dep.type.className(), dep.key.qualifier)
        return resolveExpression(key, type, dep.deferred)
    }

    private fun resolveExpression(
        key: CodeBlock,
        type: TypeName,
        deferred: DeferredKind,
    ): CodeBlock {
        val method = when (deferred) {
            DeferredKind.NONE -> "resolve"
            DeferredKind.PROVIDER -> "provider"
            DeferredKind.LAZY -> "deferred"
        }
        return CodeBlock.of("resolver.%L<%T>(%L, scope)", method, type, key)
    }

    /**
     * `Key(Foo::class.java)` — always a class reference, never an FQN string literal:
     * R8 then renames the key together with the class, and no source name ships.
     */
    internal fun keyLiteral(
        type: ClassName,
        qualifier: String?,
        element: ClassName? = null,
        mapValue: ClassName? = null,
    ): CodeBlock {
        val literal = CodeBlock.builder().add("%T(%T::class.java", RuntimeNames.KEY, type)
        if (qualifier != null) literal.add(", qualifier = %S", qualifier)
        if (element != null) literal.add(", element = %T::class.java", element)
        if (mapValue != null) literal.add(", mapValue = %T::class.java", mapValue)
        return literal.add(")").build()
    }
}
