package com.kite.di.processor.codegen

import com.kite.di.graph.DeferredKind
import com.kite.di.graph.Key
import com.kite.di.processor.model.BindingModel
import com.kite.di.processor.model.DependencyModel
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.SET
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec

/**
 * Emits one reflection-free `<Type>_Factory` per inferred binding, in the
 * target's own package (so `internal` classes stay accessible).
 */
object FactoryGenerator {

    fun factoryFile(binding: BindingModel, availableKeys: Set<Key>): FileSpec {
        val producedType = binding.keyType.className()
        val create = FunSpec.builder("create")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("resolver", RuntimeNames.RESOLVER)
            .addParameter("scope", RuntimeNames.SCOPE_NODE)
            .returns(producedType)

        val args = CodeBlock.builder()
        val included = binding.dependencies.filter { !it.optional || it.key in availableKeys }
        for (dep in included) {
            // Named arguments so optional params with missing bindings can be omitted.
            args.add("%L = %L,\n", dep.paramName, resolveExpression(dep))
        }

        val callArgs = CodeBlock.builder().add("(\n").indent().add(args.build()).unindent().add(")")
        create.addCode(
            CodeBlock.builder().add("return %T", binding.targetType.className()).add(callArgs.build()).build()
        )

        val type = TypeSpec.classBuilder(binding.factoryName)
            // Same visibility as what it constructs: a public factory returning an
            // internal type does not compile.
            .apply { if (binding.internal) addModifiers(KModifier.INTERNAL) }
            .addKdoc(
                "Generated by the Kite processor from %L (%L) — do not edit.",
                binding.declaration,
                inferenceReason(binding),
            )
            .addSuperinterface(RuntimeNames.FACTORY.parameterizedBy(producedType))
            .addFunction(create.build())
        return FileSpec.builder(binding.factoryPackage, binding.factoryName)
            .addType(type.build())
            .build()
    }

    private fun inferenceReason(binding: BindingModel): String = when (binding.inferredBy) {
        com.kite.di.processor.model.InferredBy.IMPLEMENTATION ->
            if (binding.extraKeyTypes.isNotEmpty()) {
                "implementation of ${binding.extraKeyTypes.joinToString { it.displayName }}"
            } else {
                "implementation"
            }
        com.kite.di.processor.model.InferredBy.ROOT_RULE -> "root rule in graph.rules"
        com.kite.di.processor.model.InferredBy.CLOSURE -> "constructor dependency"
    }

    internal fun resolveExpression(dep: DependencyModel): CodeBlock {
        val type: TypeName = dep.setElement?.let { SET.parameterizedBy(it.className()) }
            ?: dep.type.className()
        val key = dep.setElement?.let { keyLiteral(SET, qualifier = null, element = it.className()) }
            ?: keyLiteral(dep.type.className(), dep.key.qualifier)
        return resolveExpression(key, type, dep.deferred)
    }

    private fun resolveExpression(
        key: CodeBlock,
        type: TypeName,
        deferred: DeferredKind,
    ): CodeBlock {
        val method = when (deferred) {
            DeferredKind.NONE -> "resolve"
            DeferredKind.PROVIDER -> "provider"
            DeferredKind.LAZY -> "deferred"
        }
        return CodeBlock.of("resolver.%L<%T>(%L, scope)", method, type, key)
    }

    /**
     * `Key(Foo::class.java)` — always a class reference, never an FQN string literal:
     * R8 then renames the key together with the class, and no source name ships.
     * Graph arguments carry the leaf parameter name as the qualifier — a plain
     * string, not a class name, so nothing leaks.
     */
    internal fun keyLiteral(
        type: ClassName,
        qualifier: String?,
        element: ClassName? = null,
    ): CodeBlock {
        val literal = CodeBlock.builder().add("%T(%T::class.java", RuntimeNames.KEY, type)
        if (qualifier != null) literal.add(", qualifier = %S", qualifier)
        if (element != null) literal.add(", element = %T::class.java", element)
        return literal.add(")").build()
    }
}
