package com.kite.di.processor.codegen

import com.kite.di.processor.model.BindingModel
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec

/**
 * Emits `<Type>_Key` for an `internal` binding: a public object holding that
 * binding's [com.kite.di.runtime.Key].
 *
 * The application module assembles the bindings whose correctness needs the whole
 * application — which interface resolves to which implementation, what a `Set<I>`
 * contains — and to name an element it needs that element's key. It cannot write
 * `Key(FileRequestCache::class.java)` for another module's `internal` class, and
 * Kite generates Kotlin, so `internal` is a real wall rather than the JVM-public
 * name it is to a Java generator like Dagger's.
 *
 * So the owning module, where the class *is* visible, publishes the key instead.
 * The class is never named outside; only this handle is, and its name follows
 * from the type's, so no metadata has to carry it.
 *
 * Public bindings get none of this — the application names those directly.
 */
object KeyHandleGenerator {

    fun handleName(binding: BindingModel): String =
        binding.targetType.simpleNames.joinToString("_") + "_Key"

    fun handleFile(binding: BindingModel): FileSpec? {
        if (!binding.internal) return null
        val name = handleName(binding)
        val holder = TypeSpec.objectBuilder(name)
            .addKdoc(
                "Public handle for the internal binding %L — generated by the Kite processor, do not edit.",
                binding.declaration,
            )
            .addProperty(
                PropertySpec.builder("KEY", RuntimeNames.KEY, KModifier.PUBLIC)
                    .initializer(
                        CodeBlock.of("%T(%T::class.java)", RuntimeNames.KEY, binding.targetType.className()),
                    )
                    .build(),
            )
            .build()
        return FileSpec.builder(binding.factoryPackage, name)
            .addType(holder)
            .build()
    }
}
