package com.kite.di.processor.codegen

import com.kite.di.processor.model.BindingModel
import com.kite.di.processor.model.GraphArg
import com.kite.di.processor.model.SetBindingModel
import com.kite.di.processor.model.TypeRef
import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LIST
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.SET
import com.squareup.kotlinpoet.TypeSpec

/**
 * Emits the per-Gradle-module `<Module>_BindingRegistry` and — in the application
 * module (`kite.aggregate=true`) — the `MergedRegistry` that `Kite.init()`
 * loads. Bindings are sorted by key id so output is deterministic. The registry
 * carries the module's graph arguments as a `@GraphArgs` annotation, which the
 * application module's KSP run reads off the classpath to compose `Graph.start`.
 */
object RegistryGenerator {

    fun registryName(moduleName: String): String = sanitizeModuleName(moduleName) + "_BindingRegistry"

    fun registryFile(
        moduleName: String,
        bindings: List<BindingModel>,
        setBindings: List<SetBindingModel>,
        graphArgs: List<GraphArg>,
        /** This module's interfaces with >1 implementation and no `@Bind` decision. */
        ambiguousInterfaces: List<TypeRef> = emptyList(),
        /** false for user-facing builds: no file/line strings in the shipped binary. */
        includeProvenance: Boolean = true,
    ): FileSpec {
        val name = registryName(moduleName)

        val bindingsFun = FunSpec.builder("bindings")
            .addModifiers(KModifier.OVERRIDE)
            .returns(LIST.parameterizedBy(RuntimeNames.BINDING_RECORD))
            .addCode(
                CodeBlock.builder()
                    .add("return listOf(\n")
                    .indent()
                    .apply {
                        for (b in bindings.sortedBy { it.key.id }) {
                            add("%L,\n", recordLiteral(b, includeProvenance))
                        }
                        for (set in setBindings.sortedBy { it.key.id }) {
                            add("%L,\n", setRecordLiteral(set, includeProvenance))
                        }
                    }
                    .unindent()
                    .add(")")
                    .build()
            )

        val type = TypeSpec.classBuilder(name)
            .addKdoc("Generated by the Kite processor for module %L — do not edit.", moduleName)
            .addSuperinterface(RuntimeNames.BINDING_REGISTRY)
            .addFunction(bindingsFun.build())
        providedKeysAnnotation(moduleName, bindings, ambiguousInterfaces)?.let(type::addAnnotation)
        if (graphArgs.isNotEmpty()) {
            val annotation = AnnotationSpec.builder(RuntimeNames.GRAPH_ARGS)
                .addMember(
                    "names = [%L]",
                    graphArgs.sortedBy { it.name }.joinToString { "\"${it.name}\"" },
                )
                .addMember(
                    "types = [%L]",
                    CodeBlock.builder().apply {
                        graphArgs.sortedBy { it.name }.forEachIndexed { i, arg ->
                            if (i > 0) add(", ")
                            add("%T::class", arg.type.className())
                        }
                    }.build(),
                )
                .build()
            type.addAnnotation(annotation)
        }
        return FileSpec.builder(RuntimeNames.GENERATED_PACKAGE, name).addType(type.build()).build()
    }

    /**
     * `@ProvidedKeys(...)` — the module's exported keys (own classes + the interfaces
     * they are bound to, with their scopes) plus its unresolved ambiguities.
     * Downstream modules' KSP runs read this off the classpath to resolve
     * cross-module constructor parameters. Class references and logical names only.
     */
    private fun providedKeysAnnotation(
        moduleName: String,
        bindings: List<BindingModel>,
        ambiguousInterfaces: List<TypeRef>,
    ): AnnotationSpec? {
        data class Provided(val type: TypeRef, val scopeName: String?, val scopeLevel: Int?)

        val provided = buildList {
            for (b in bindings) {
                add(Provided(b.keyType, b.scopeName, b.scopeLevel))
                for (t in b.extraKeyTypes) add(Provided(t, b.scopeName, b.scopeLevel))
            }
        }.distinctBy { it.type.fqn }.sortedBy { it.type.fqn }
        if (provided.isEmpty() && ambiguousInterfaces.isEmpty()) return null

        val builder = AnnotationSpec.builder(RuntimeNames.PROVIDED_KEYS)
            .addMember("module = %S", moduleName)
            .addMember(
                "types = [%L]",
                CodeBlock.builder().apply {
                    provided.forEachIndexed { i, p ->
                        if (i > 0) add(", ")
                        add("%T::class", p.type.className())
                    }
                }.build(),
            )
            .addMember("scopeNames = [%L]", provided.joinToString { "\"${it.scopeName ?: ""}\"" })
            .addMember("scopeLevels = [%L]", provided.joinToString { (it.scopeLevel ?: Int.MIN_VALUE).toString() })
        if (ambiguousInterfaces.isNotEmpty()) {
            builder.addMember(
                "ambiguous = [%L]",
                CodeBlock.builder().apply {
                    ambiguousInterfaces.sortedBy { it.fqn }.forEachIndexed { i, t ->
                        if (i > 0) add(", ")
                        add("%T::class", t.className())
                    }
                }.build(),
            )
        }
        return builder.build()
    }

    /** `MergedRegistry.load()` — own registry plus every registry found on the compile classpath. */
    fun mergedRegistryFile(ownRegistryName: String, classpathRegistryFqns: List<String>): FileSpec {
        val all = (listOf("${RuntimeNames.GENERATED_PACKAGE}.$ownRegistryName") + classpathRegistryFqns)
            .distinct().sorted()
        val load = FunSpec.builder("load")
            .returns(LIST.parameterizedBy(RuntimeNames.BINDING_REGISTRY))
            .addCode(
                CodeBlock.builder()
                    .add("return listOf(\n")
                    .indent()
                    .apply {
                        for (fqn in all) {
                            add("%T(),\n", ClassName(fqn.substringBeforeLast('.'), fqn.substringAfterLast('.')))
                        }
                    }
                    .unindent()
                    .add(")")
                    .build()
            )
        val type = TypeSpec.objectBuilder("MergedRegistry")
            .addKdoc("Generated aggregate loaded by Kite.init() — do not edit.")
            .addFunction(load.build())
        return FileSpec.builder(RuntimeNames.GENERATED_PACKAGE, "MergedRegistry").addType(type.build()).build()
    }

    /** One BindingRecord aggregating every implementation of the set's element type. */
    private fun setRecordLiteral(set: SetBindingModel, includeProvenance: Boolean): CodeBlock {
        val builder = CodeBlock.builder()
            .add("%T(\n", RuntimeNames.BINDING_RECORD)
            .indent()
            .add("key = %L,\n", FactoryGenerator.keyLiteral(SET, qualifier = null, element = set.elementType.className()))
            .add("factory = %T(listOf(", RuntimeNames.SET_FACTORY)
        set.elementTypes.forEachIndexed { i, element ->
            if (i > 0) builder.add(", ")
            builder.add("%L", FactoryGenerator.keyLiteral(element.className(), qualifier = null))
        }
        builder.add(")),\n")
        if (includeProvenance) {
            // declaration/provenance carry source names — dev builds only.
            builder.add("declaration = %S,\n", "Set<${set.elementType.displayName}> (${set.elementKeys.size} implementations)")
            builder.add(
                "provenance = %T(%S, %S, %L),\n",
                RuntimeNames.PROVENANCE,
                set.provenance.gradleModule,
                set.provenance.filePath,
                set.provenance.line,
            )
        }
        return builder.unindent().add(")").build()
    }

    private fun recordLiteral(b: BindingModel, includeProvenance: Boolean): CodeBlock {
        val builder = CodeBlock.builder()
            .add("%T(\n", RuntimeNames.BINDING_RECORD)
            .indent()
            .add("key = %L,\n", FactoryGenerator.keyLiteral(b.keyType.className(), b.key.qualifier))
            .add("factory = %T(),\n", ClassName(b.factoryPackage, b.factoryName))
        if (b.extraKeys.isNotEmpty()) {
            builder.add("extraKeys = listOf(")
            b.extraKeys.zip(b.extraKeyTypes).forEachIndexed { i, (k, t) ->
                if (i > 0) builder.add(", ")
                builder.add("%L", FactoryGenerator.keyLiteral(t.className(), k.qualifier))
            }
            builder.add("),\n")
        }
        if (b.scopeLevel != null) {
            builder.add("scopeLevel = %L,\n", b.scopeLevel)
            builder.add("scopeName = %S,\n", b.scopeName)
        }
        if (includeProvenance) {
            // declaration/provenance carry source names — dev builds only.
            builder.add("declaration = %S,\n", b.declaration)
            builder.add(
                "provenance = %T(%S, %S, %L),\n",
                RuntimeNames.PROVENANCE,
                b.provenance.gradleModule,
                b.provenance.filePath,
                b.provenance.line,
            )
        }
        return builder.unindent().add(")").build()
    }
}
