package com.kite.di.processor.codegen

import com.kite.di.processor.model.BindingModel
import com.kite.di.processor.model.MemberInjectModel
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LIST
import com.squareup.kotlinpoet.MAP
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.SET
import com.squareup.kotlinpoet.STAR
import com.squareup.kotlinpoet.TypeSpec

/**
 * Emits the per-Gradle-module `<Module>_BindingRegistry` and — in the application
 * module (`kite.aggregate=true`) — the `MergedRegistry` that `Kite.init()`
 * loads. Bindings are sorted by key id so output is deterministic.
 */
object RegistryGenerator {

    fun registryName(moduleName: String): String = sanitizeModuleName(moduleName) + "_BindingRegistry"

    fun registryFile(
        moduleName: String,
        bindings: List<BindingModel>,
        memberInjects: List<MemberInjectModel>,
        /** false for user-facing builds: no file/line strings in the shipped binary. */
        includeProvenance: Boolean = true,
    ): FileSpec {
        val name = registryName(moduleName)

        val unique = bindings.filter { !it.isContribution }
        val sets = bindings.filter { it.intoSet }.groupBy { it.setKey!! }
        val maps = bindings.filter { it.intoMapKey != null }.groupBy { it.mapKey!! }
        val bindingsFun = FunSpec.builder("bindings")
            .addModifiers(KModifier.OVERRIDE)
            .returns(LIST.parameterizedBy(RuntimeNames.BINDING_RECORD))
            .addCode(
                CodeBlock.builder()
                    .add("return listOf(\n")
                    .indent()
                    .apply {
                        for (b in unique.sortedBy { it.key.id }) {
                            add("%L,\n", recordLiteral(b, includeProvenance))
                        }
                        for ((setKey, contributions) in sets.entries.sortedBy { it.key.id }) {
                            add("%L,\n", setRecordLiteral(setKey, contributions, includeProvenance))
                        }
                        for ((mapKey, contributions) in maps.entries.sortedBy { it.key.id }) {
                            add("%L,\n", mapRecordLiteral(mapKey, contributions, includeProvenance))
                        }
                    }
                    .unindent()
                    .add(")")
                    .build()
            )

        val injectorsFun = FunSpec.builder("memberInjectors")
            .addModifiers(KModifier.OVERRIDE)
            .returns(
                MAP.parameterizedBy(
                    RuntimeNames.JAVA_CLASS.parameterizedBy(STAR),
                    RuntimeNames.MEMBER_INJECTOR.parameterizedBy(STAR),
                )
            )
            .addCode(
                CodeBlock.builder()
                    .add("return mapOf(\n")
                    .indent()
                    .apply {
                        for (m in memberInjects.sortedBy { it.targetType.fqn }) {
                            // Class-keyed, not FQN strings: rename-safe and leak-free.
                            add(
                                "%T::class.java to %T(),\n",
                                m.targetType.className(),
                                ClassName(m.targetType.packageName, m.injectorName),
                            )
                        }
                    }
                    .unindent()
                    .add(")")
                    .build()
            )

        val type = TypeSpec.classBuilder(name)
            .addKdoc("Generated by the Kite processor for module %L — do not edit.", moduleName)
            .addSuperinterface(RuntimeNames.BINDING_REGISTRY)
            .addFunction(bindingsFun.build())
            .addFunction(injectorsFun.build())
        return FileSpec.builder(RuntimeNames.GENERATED_PACKAGE, name).addType(type.build()).build()
    }

    /** `MergedRegistry.load()` — own registry plus every registry found on the compile classpath. */
    fun mergedRegistryFile(ownRegistryName: String, classpathRegistryFqns: List<String>): FileSpec {
        val all = (listOf("${RuntimeNames.GENERATED_PACKAGE}.$ownRegistryName") + classpathRegistryFqns)
            .distinct().sorted()
        val load = FunSpec.builder("load")
            .returns(LIST.parameterizedBy(RuntimeNames.BINDING_REGISTRY))
            .addCode(
                CodeBlock.builder()
                    .add("return listOf(\n")
                    .indent()
                    .apply {
                        for (fqn in all) {
                            add("%T(),\n", ClassName(fqn.substringBeforeLast('.'), fqn.substringAfterLast('.')))
                        }
                    }
                    .unindent()
                    .add(")")
                    .build()
            )
        val type = TypeSpec.objectBuilder("MergedRegistry")
            .addKdoc("Generated aggregate loaded by Kite.init() — do not edit.")
            .addFunction(load.build())
        return FileSpec.builder(RuntimeNames.GENERATED_PACKAGE, "MergedRegistry").addType(type.build()).build()
    }

    /** One BindingRecord aggregating all @IntoSet contributions of a Set<T> key. */
    private fun setRecordLiteral(
        setKey: com.kite.di.graph.Key,
        contributions: List<BindingModel>,
        includeProvenance: Boolean,
    ): CodeBlock {
        val element = contributions.first().keyType
        val builder = CodeBlock.builder()
            .add("%T(\n", RuntimeNames.BINDING_RECORD)
            .indent()
            .add("key = %L,\n", FactoryGenerator.keyLiteral(SET, setKey.qualifier, element.className()))
            .add("factory = %T(listOf(", RuntimeNames.SET_FACTORY)
        contributions.forEachIndexed { i, c ->
            if (i > 0) builder.add(", ")
            builder.add("%T()", ClassName(c.factoryPackage, c.factoryName))
        }
        builder.add(")),\n")
        val first = contributions.first()
        if (includeProvenance) {
            // declaration/provenance carry source names — dev builds only.
            builder.add("declaration = %S,\n", "Set<${element.displayName}> (${contributions.size} contributions)")
            builder.add(
                "provenance = %T(%S, %S, %L),\n",
                RuntimeNames.PROVENANCE,
                first.provenance.gradleModule,
                first.provenance.filePath,
                first.provenance.line,
            )
        }
        return builder.unindent().add(")").build()
    }

    /** One BindingRecord aggregating all @IntoMap contributions of a Map<String, V> key. */
    private fun mapRecordLiteral(
        mapKey: com.kite.di.graph.Key,
        contributions: List<BindingModel>,
        includeProvenance: Boolean,
    ): CodeBlock {
        val value = contributions.first().keyType
        val builder = CodeBlock.builder()
            .add("%T(\n", RuntimeNames.BINDING_RECORD)
            .indent()
            .add("key = %L,\n", FactoryGenerator.keyLiteral(MAP, mapKey.qualifier, mapValue = value.className()))
            .add("factory = %T(mapOf(", RuntimeNames.MAP_FACTORY)
        contributions.forEachIndexed { i, c ->
            if (i > 0) builder.add(", ")
            builder.add("%S to %T()", c.intoMapKey, ClassName(c.factoryPackage, c.factoryName))
        }
        builder.add(")),\n")
        val first = contributions.first()
        if (includeProvenance) {
            // declaration/provenance carry source names — dev builds only.
            builder.add("declaration = %S,\n", "Map<String, ${value.displayName}> (${contributions.size} entries)")
            builder.add(
                "provenance = %T(%S, %S, %L),\n",
                RuntimeNames.PROVENANCE,
                first.provenance.gradleModule,
                first.provenance.filePath,
                first.provenance.line,
            )
        }
        return builder.unindent().add(")").build()
    }

    private fun recordLiteral(b: BindingModel, includeProvenance: Boolean): CodeBlock {
        val builder = CodeBlock.builder()
            .add("%T(\n", RuntimeNames.BINDING_RECORD)
            .indent()
            .add("key = %L,\n", FactoryGenerator.keyLiteral(b.keyType.className(), b.key.qualifier))
            .add("factory = %T(),\n", ClassName(b.factoryPackage, b.factoryName))
        if (b.extraKeys.isNotEmpty()) {
            builder.add("extraKeys = listOf(")
            b.extraKeys.zip(b.extraKeyTypes).forEachIndexed { i, (k, t) ->
                if (i > 0) builder.add(", ")
                builder.add("%L", FactoryGenerator.keyLiteral(t.className(), k.qualifier))
            }
            builder.add("),\n")
        }
        if (b.scopeLevel != null) {
            builder.add("scopeLevel = %L,\n", b.scopeLevel)
            builder.add("scopeName = %S,\n", b.scopeName)
        }
        if (includeProvenance) {
            // declaration/provenance carry source names — dev builds only.
            builder.add("declaration = %S,\n", b.declaration)
            builder.add(
                "provenance = %T(%S, %S, %L),\n",
                RuntimeNames.PROVENANCE,
                b.provenance.gradleModule,
                b.provenance.filePath,
                b.provenance.line,
            )
        }
        return builder.unindent().add(")").build()
    }
}
