plugins {
    `java-gradle-plugin`
    // Not `kotlin-dsl`: Gradle's embedded Kotlin (2.2.x) cannot read the Kotlin 2.3
    // metadata of the KSP Gradle plugin we compile against — use the repo's Kotlin.
    alias(libs.plugins.kotlin.jvm)
    // Inside this repo the plugin is consumed through includeBuild and needs no
    // coordinates. A consumer outside it has only the marker to go by, so the
    // release has to publish one — `java-gradle-plugin` generates the marker
    // publication, and this carries it to Central alongside the plugin jar.
    alias(libs.plugins.maven.publish)
    alias(libs.plugins.dokka)
}

dependencies {
    // compileOnly: both are already on the consuming build's classpath (the root
    // build declares them `apply false`), so we must not ship a second copy.
    compileOnly("com.google.devtools.ksp:symbol-processing-gradle-plugin:${libs.versions.ksp.get()}")
    compileOnly("com.android.tools.build:gradle-api:${libs.versions.agp.get()}")
}

gradlePlugin {
    plugins {
        create("kite") {
            id = "com.kitedi"
            implementationClass = "com.kite.di.gradle.KitePlugin"
        }
    }
}

// The coordinates the plugin hands a consumer's build (`runtime`, `processor`,
// `rules`, `compose`, `board`) must be the ones this plugin itself was published
// under — generate them instead of hand-syncing a constant, so a version bump
// can never leave consumers pointing at artifacts that do not exist.
val kiteGroup = providers.gradleProperty("GROUP").get()
val kiteVersion = providers.gradleProperty("VERSION_NAME").get()
val generateCoordinates = tasks.register("generateKiteCoordinates") {
    description = "Generates Coordinates.kt from this build's GROUP/VERSION_NAME."
    val outputDir = layout.buildDirectory.dir("generated/source/kiteCoordinates")
    inputs.property("group", kiteGroup)
    inputs.property("version", kiteVersion)
    outputs.dir(outputDir)
    doLast {
        val file = outputDir.get().file("com/kite/di/gradle/Coordinates.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            // Generated by the build from GROUP/VERSION_NAME — do not edit.
            package com.kite.di.gradle

            internal const val KITE_GROUP: String = "$kiteGroup"
            internal const val KITE_VERSION: String = "$kiteVersion"

            """.trimIndent(),
        )
    }
}

kotlin.sourceSets.named("main") { kotlin.srcDir(generateCoordinates) }
